export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
//export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE'

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS'
export const FILTER_PRODUCTS_FAILURE = 'FILTER_PRODUCTS_FAILURE'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
